$(document).ready(function(){
  $(".popup").focus(function(){
    $(".options").css("display","block");
    $(".options").css("opacity","1");
  });
  $(".popup").focusout(function(){
    $(".options").css("display","none");
    $(".options").css("opacity","0");
  });
  $(".slideToggle").focus(function(){
     $(".slidenav").attr("expand","true"); 
  });
  $(".slideToggle").focusout(function(){
    $(".slidenav").attr("expand","false");
  });
});
